# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

main_wrap <- function(args, verbose, method) {
    .Call('_SCOUP_main_wrap', PACKAGE = 'SCOUP', args, verbose, method)
}

